name: build-cache

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: pull
#        env:
#          CURRENT_BRANCH:  ${{ github.head_ref || github.ref_name }}
#        run: |
#          CURRENT_BRANCH=main docker-compose -f "docker-compose.ci.yml" pull ci || true
#          docker-compose -f "docker-compose.ci.yml" pull ci || true
#          docker-compose -f "docker-compose.ci.yml" pull release || true

      - uses: whoan/docker-build-with-cache-action@v5
        env:
          CURRENT_BRANCH:  ${{ github.head_ref || github.ref_name }}
        with:
          username: sparrovv
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
#          compose_file: docker-compose.ci.yml
          image_name: "ghcr.io/sparrovv/poetry-test-app"
          image_tag: ci-${{ github.head_ref || github.ref_name }}
          pull_image_and_stages: true
          push_image_and_stages: false
          build_extra_args: '{"--build-arg": ["REVISION=${GITHUB_SHA}", "CURRENT_BRANCH=main"]}'

      - name: Display images
        run: docker images

      - name: run tests
        env:
          CURRENT_BRANCH:  ${{ github.head_ref || github.ref_name }}
        run: docker-compose -f "docker-compose.ci.yml" run ci pytest

#      - uses: whoan/docker-build-with-cache-action@v5
#        env:
#          CURRENT_BRANCH:  ${{ github.head_ref || github.ref_name }}
#        with:
#          username: sparrovv
#          password: "${{ secrets.GITHUB_TOKEN }}"
#          registry: ghcr.io
#          compose_file: docker-compose.ci.yml
#          image_name: "ghcr.io/sparrovv/poetry-test-app"
#          image_tag: ci-${{ github.head_ref || github.ref_name }}
#          pull_image_and_stages: true
#          push_image_and_stages: true

#      - name: release images
#        env:
#          CURRENT_BRANCH:  ${{ github.head_ref || github.ref_name }}
#          IMAGE_NAME: "ghcr.io/sparrovv/poetry-test-app"
#        run: |
#          docker-compose -f "docker-compose.ci.yml" push ci
#
#          docker tag $IMAGE_NAME:ci-$CURRENT_BRANCH $IMAGE_NAME:ci-${{ github.sha }}
#          docker push $IMAGE_NAME:ci-${{ github.sha }}
#
#          docker-compose -f "docker-compose.ci.yml" build release
#          docker-compose -f "docker-compose.ci.yml" push release
#
#          docker tag $IMAGE_NAME:release $IMAGE_NAME:release-${{ github.sha }}
#          docker push $IMAGE_NAME:release-${{ github.sha }}